server:
  port: 9000


#mail config
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: your email address
    password: your pass
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

#h2 database
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2

app:
  mail:
    verficationURL: http://localhost:9000/activation?token=